### PR TITLE
config: Improve default value message

### PR DESCRIPTION
**Pull request by cfergeau**
This follows the advice from https://github.com/crc-org/crc/pull/3694#discussion_r1213896610

### CODE REVIEW

**Review by gbraad — APPROVED** [review]

**Comment by cfergeau** [comment]
added a commit to try to see why microshift is failing.

**Comment by cfergeau** [comment]
> added a commit to try to see why microshift is failing.

Could be just general runner slowness? The log has `Jun 05 23:38:26 api.crc.testing systemd[1]: microshift.service: start operation timed out. Terminating. `

See also
```
2023-06-06T03:36:02.2329830Z level=debug msg="Using root access: Starting microshift service"
2023-06-06T03:36:02.2330310Z level=debug msg="Running SSH command: sudo systemctl start microshift"
2023-06-06T03:38:29.0338710Z level=debug msg="SSH command results: err: Process exited with status 1, output: "
```

2min30s between `systemctl start` and the failure, feels quite long?

**Comment by anjannath** [comment]
@cfergeau can you please remove the "CI debug" commit, we can merge this, the microshift CI issue is at least not happening locally on the mac

**Pull request merged**
