### PR TITLE
actions: add windows e2e

### PR DESCRIPTION
**Pull request by jsliacan**
**Fixes:** Issue #3961

### CODE REVIEW

**Comment by praveenkumar** [comment]
Is this a [WIP] or ready for review PR?

**Comment by jsliacan** [comment]
@praveenkumar it's just the bot casually removing the `do-not-merge` label. Sorry, didn't notice.

**Comment by gbraad** [comment]
@adrianriobo Why did you add the hold label; perhaps it was WIP instead?

**Comment by anjannath** [comment]
The `Windows e2e` action is not getting triggered, from the action yaml, it should get triggered once the `Build Windows installer` is finished running

**Comment by jsliacan** [comment]
@anjannath thanks. That's because it needs secrets etc. and therefore workflow_run triggered flows only work if they're on the default branch (main in our upstream case). So in other words, it'll only work once merged. However, I set up an analogous situation with windows-installer and build-images workflows on my fork (where I have access to secrets and can designate any branch as default) and it works: https://github.com/jsliacan/crc/actions/runs/7098881034. But I need to polish it a little before I remove the hold label.

**Review by anjannath — APPROVED** [review]
LGTM

successful run on jsliacans fork https://github.com/jsliacan/crc/actions/runs/7206156919

**Comment by jsliacan** [comment]
It seems that I still need to display test results among the upstream PR checks (they run on the fork, but the workflow with windows-e2e runs on the default branch of the upstream repository). So one needs to take the results, when ready, and post them back on the PR that triggered the workflow which then triggered the windows-e2e workflow.

**Pull request merged**
