### PR TITLE
build: Simplify/improve verify-vendor.sh

### PR DESCRIPTION
**Pull request by cfergeau**
`verify-vendor.sh` compares the content of the `vendor` directory after
running `make vendor` with a copy which was made before running `make
vendor`.
This does not catch changes to go.mod/go.sum made by `go mod tidy` which
we forgot to commit.

This commit uses `git diff --exit-code` instead of running `diff` against the
vendor directory.

This will catch all uncommitted changes, which should be fine when `make
vendorcheck` is run.

Using `git diff` instead of `diff` allows to remove quite some code from
`verify-vendor.sh`

### CODE REVIEW

**Comment by cfergeau** [comment]
The "Build RPM" failure means this change is working as expected. However, I realize now that it would be good if `make spec` failed when `gomod2rpmdeps` fails.

**Comment by praveenkumar** [comment]
About https://github.com/crc-org/crc/pull/4132/commits/07add4ff6a24d2fd918251c1014268a24ded50e2 I was thinking instead to use go-1.21 tool chain can we revert ec6cbfb3d35f433a6285bda4b12badb45e97f915 one and use `go mod tidy -go 1.20` as part of `make vendor` ?

**Comment by praveenkumar** [comment]
should we close it because #4139 have all those commits also?

**Comment by cfergeau** [comment]
Since this PR won't work without updating to 1.21, sure.

**Pull request closed without merging**
