### PR TITLE
bump openshift version to 4.12.1 and update bundle hash

### PR DESCRIPTION
**Pull request by anjannath**
4.12.1 bundles are mirrored, https://developers.redhat.com/content-gateway/rest/mirror2/pub/openshift-v4/clients/crc/bundles/openshift/4.12.1/

### CODE REVIEW

**Review by cfergeau — APPROVED** [review]
Looks good to me!

**Review by gbraad — APPROVED** [review]
/lgtm

**Comment by anjannath** [comment]
Certificate rotation test is failing consistently, but merging since the bundles have certs with 1 year validity

**Pull request merged**
