### PR TITLE
bump microshift openshift to 4.12.13 and update bundle hashes

### PR DESCRIPTION
**Pull request by anjannath**

### CODE REVIEW

**Comment by cfergeau** [comment]
/lgtm

There are several failures in the github actions checks, better to make sure they are temporary issues before pushing this.

**Comment by cfergeau** [comment]
/approve
(GH CI is green now)

**Comment by praveenkumar** [comment]
@anjannath we might need to push that bundle to GCP for integration and e2e-crc test.

**Comment by anjannath** [comment]
> @anjannath we might need to push that bundle to GCP for integration and e2e-crc test.

ahh, right, the extraction was failing for `crc setup` (and i verified the bundles on mirror are okay..) let me push the bundles to GCP then, is it using the bundle with `-b` flag for the tests then?

**Pull request merged**
