### PR TITLE
[QE] Set back e2e and integration builder image to go-toolset:1.19 

### LINKED ISSUE #3887: [QE] Wrong base images for e2e and integration container images
The builder image used on the `e2e` and `integration` Dockerfiles does not exists, as so when trying to build them we got an error like:

```
CRC_E2E_IMG_VERSION=v2.29.0-dev make containerized_e2e
rm -rf /home/ariobolo/01WORKSPACE/04SOURCE/github/crc/docs/build
rm -f packaging/darwin/Distribution
rm -f packaging/darwin/Resources/welcome.html
rm -f packaging/darwin/scripts/postinstall
rm -rf packaging/darwin/root-crc/
rm -rf packaging/darwin/root-crc-tray/
rm -rf packaging/windows/msi
rm -f out/linux-amd64/split
rm -f packaging/rpm/crc.spec images/rpmbuild/Containerfile
rm -rf out
rm -f /home/ariobolo/go/bin/crc
rm -rf release
podman build -t quay.io/crcont/crc-e2e:v2.29.0-dev -f images/build-e2e/Dockerfile .
[1/2] STEP 1/5: FROM registry.access.redhat.com/ubi8/go-toolset:1.20 AS builder
Trying to pull registry.access.redhat.com/ubi8/go-toolset:1.20...
Error: error creating build container: initializing source docker://registry.access.redhat.com/ubi8/go-toolset:1.20: reading manifest 1.20 in registry.access.redhat.com/ubi8/go-toolset: manifest unknown: manifest unknown
make: *** [Makefile:199: containerized_e2e] Error 125
```

### PR DESCRIPTION
**Pull request by adrianriobo**
Fixes #3887

### CODE REVIEW

**Comment by praveenkumar** [comment]
As part of crc codebase we are in progress to use go-1.20.x but I think for integration/e2e test binary we can still keep consuming 1.19.x as long as there is no issue running those.

**Comment by adrianriobo** [comment]
yeah no specific code for `1.20` on those components + once go-toolset 1.20 is released I will upgrade it back

**Comment by cfergeau** [comment]
This is also addressed in https://github.com/crc-org/crc/pull/3861/commits/18bb72868cc22e648ea1d51b2e94b22a353f5a70 but the PR is currently held by https://github.com/openshift/release/pull/44572 :-/

**Comment by praveenkumar** [comment]
Does registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.20-openshift-4.15 doesn't require any auth to pull images because it will pass in CI but standalone for testing purpose it will fail?

**Comment by cfergeau** [comment]
> Does registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.20-openshift-4.15 doesn't require any auth to pull images because it will pass in CI but standalone for testing purpose it will fail?

The commit log says
>  This commit switches to registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.20-opens which has golang 1.20 and **is usable without authentication.**

Iirc, I tested it in a freshly installed VM and it did not ask for any auths.

**Comment by cfergeau** [comment]
> As part of crc codebase we are in progress to use go-1.20.x but I think for integration/e2e test binary we can still keep consuming 1.19.x as long as there is no issue running those.

crc git master does not build with golang 1.21 which is the latest stable golang release. If we want to fix this, then crc git master will no longer build with golang 1.19. We have to move away from golang 1.19. But we can unblock e2e/... with this PR and I'll address this in https://github.com/crc-org/crc/pull/3861

**Comment by adrianriobo** [comment]
> I tested it in a freshly installed VM

You tested the `make containerized_e2e` or the image ... I mean did not pull it but I assume it already has `make` right?

If that is the case I am fine with moving away from go-toolset (maybe it can be used on `crc-cloud` as there we are stick to go-toolset), and I can close this PR and just use yours for building the images (or change locally)

**Comment by cfergeau** [comment]
> > I tested it in a freshly installed VM
> 
> You tested the `make containerized_e2e` or the image ... I mean did not pull it but I assume it already has `make` right?
> 
> If that is the case I am fine with moving away from go-toolset (maybe it can be used on `crc-cloud` as there we are stick to go-toolset), and I can close this PR and just use yours for building the images (or change locally)

I tested in a fresh VM/new user that I could pull the image without auth.
I also tested that I could build the image, but not necessarily on the same machine, but this should not matter.

**Comment by adrianriobo** [comment]
yeah yeah I mean does `registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.20-openshift-4.15` image have `make` already installed ?

**Comment by cfergeau** [comment]
> yeah yeah I mean does `registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.20-openshift-4.15` image have `make` already installed ?

```
$ podman build -f ./images/build-e2e/Dockerfile .
[1/2] STEP 1/6: FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.20-openshift-4.15 AS builder
[1/2] STEP 2/6: USER root
--> 8fa3324704ed
[1/2] STEP 3/6: WORKDIR /workspace
--> 8f28c33443b2
[1/2] STEP 4/6: COPY . .
--> e89321b7b581
[1/2] STEP 5/6: ENV GO_COMPLIANCE_INFO=0
--> 190c6222ed45
[1/2] STEP 6/6: RUN make build_e2e
GOARCH=amd64 GOOS=linux   go test ./test/e2e/ -tags "containers_image_openpgp" --ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.28.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.13.0-0.okd-2023-09-03-082426 -X github.com/crc-org/crc/v2/pkg/crc/version.podmanVersion=4.4.4 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=c28d75" -c -o out/linux-amd64/e2e.test
GOARCH=amd64 GOOS=windows go test ./test/e2e/ -tags "containers_image_openpgp" --ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.28.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.13.0-0.okd-2023-09-03-082426 -X github.com/crc-org/crc/v2/pkg/crc/version.podmanVersion=4.4.4 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=c28d75" -c -o out/windows-amd64/e2e.test.exe
GOARCH=amd64 GOOS=darwin  go test ./test/e2e/ -tags "containers_image_openpgp" --ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.28.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.13.0-0.okd-2023-09-03-082426 -X github.com/crc-org/crc/v2/pkg/crc/version.podmanVersion=4.4.4 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=c28d75" -c -o out/macos-amd64/e2e.test
GOARCH=arm64 GOOS=darwin  go test ./test/e2e/ -tags "containers_image_openpgp" --ldflags="-X github.com/crc-org/crc/v2/pkg/crc/version.crcVersion=2.28.0 -X github.com/crc-org/crc/v2/pkg/crc/version.ocpVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.okdVersion=4.13.0-0.okd-2023-09-03-082426 -X github.com/crc-org/crc/v2/pkg/crc/version.podmanVersion=4.4.4 -X github.com/crc-org/crc/v2/pkg/crc/version.microshiftVersion=4.13.14 -X github.com/crc-org/crc/v2/pkg/crc/version.commitSha=c28d75" -c -o out/macos-arm64/e2e.test
--> 7050ef805917
[2/2] STEP 1/9: FROM registry.access.redhat.com/ubi8/ubi-minimal
[2/2] STEP 2/9: LABEL MAINTAINER "CRC <devtools-cdk@redhat.com>"
--> 29ec2f573d24
[2/2] STEP 3/9: COPY --from=builder /workspace/images/build-e2e/entrypoint.sh /usr/local/bin/
--> 2f4831763196
[2/2] STEP 4/9: COPY --from=builder /workspace/out /opt/crc/bin
--> bdfbaea6a1a0
[2/2] STEP 5/9: COPY --from=builder /workspace/test/e2e/features /opt/crc/features
--> 49e9028e92f0
[2/2] STEP 6/9: COPY --from=builder /workspace/test/testdata /opt/crc/testdata
--> 38c0393d5f17
[2/2] STEP 7/9: ENV EPEL https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
--> 3dd289fecdca
[2/2] STEP 8/9: RUN rpm -ivh ${EPEL}     && microdnf --enablerepo=epel install -y openssh-clients sshpass     && microdnf clean all
warning: /var/tmp/rpm-tmp.tn68TX: Header V4 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
epel-release-8-19.el8                 ########################################
Many EPEL packages require the CodeReady Builder (CRB) repository.
It is recommended that you run /usr/bin/crb enable to enable the CRB repository.

(microdnf:8): librhsm-WARNING **: 13:31:31.455: Found 0 entitlement certificates

(microdnf:8): librhsm-WARNING **: 13:31:31.457: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Package                                         Repository               Size
Installing:                                                                  
 cracklib-2.9.6-15.el8.x86_64                   ubi-8-baseos-rpms     95.5 kB
 cracklib-dicts-2.9.6-15.el8.x86_64             ubi-8-baseos-rpms      4.1 MB
 gzip-1.9-13.el8_5.x86_64                       ubi-8-baseos-rpms    170.8 kB
 libedit-3.1-23.20170329cvs.el8.x86_64          ubi-8-baseos-rpms    104.5 kB
 libfdisk-2.32.1-42.el8_8.x86_64                ubi-8-baseos-rpms    259.4 kB
 libnsl2-1.2.0-2.20180605git4a062cf.el8.x86_64  ubi-8-baseos-rpms     59.1 kB
 libpwquality-1.4.4-6.el8.x86_64                ubi-8-baseos-rpms    109.7 kB
 libsemanage-2.9-9.el8_6.x86_64                 ubi-8-baseos-rpms    172.1 kB
 libtirpc-1.1.4-8.el8.x86_64                    ubi-8-baseos-rpms    115.8 kB
 libutempter-1.1.6-14.el8.x86_64                ubi-8-baseos-rpms     32.6 kB
 openssh-8.0p1-19.el8_8.x86_64                  ubi-8-baseos-rpms    536.3 kB
 openssh-clients-8.0p1-19.el8_8.x86_64          ubi-8-baseos-rpms    685.1 kB
 pam-1.3.1-25.el8.x86_64                        ubi-8-baseos-rpms    763.9 kB
 shadow-utils-2:4.6-17.el8.x86_64               ubi-8-baseos-rpms      1.3 MB
 sshpass-1.09-4.el8.x86_64                      ubi-8-appstream-rpms  30.6 kB
 util-linux-2.32.1-42.el8_8.x86_64              ubi-8-baseos-rpms      2.6 MB
Upgrading:                                                                   
 libblkid-2.32.1-42.el8_8.x86_64                ubi-8-baseos-rpms    225.4 kB
  replacing libblkid-2.32.1-39.el8_7.x86_64                                  
 libmount-2.32.1-42.el8_8.x86_64                ubi-8-baseos-rpms    241.9 kB
  replacing libmount-2.32.1-39.el8_7.x86_64                                  
 libsmartcols-2.32.1-42.el8_8.x86_64            ubi-8-baseos-rpms    183.4 kB
  replacing libsmartcols-2.32.1-39.el8_7.x86_64                              
 libuuid-2.32.1-42.el8_8.x86_64                 ubi-8-baseos-rpms    100.8 kB
   replacing libuuid-2.32.1-39.el8_7.x86_64                                  
Transaction Summary:
 Installing:       16 packages
 Reinstalling:      0 packages
 Upgrading:         4 packages
 Obsoleting:        0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
Updating: libuuid;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Updating: libblkid;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Installing: libtirpc;1.1.4-8.el8;x86_64;ubi-8-baseos-rpms
Installing: libnsl2;1.2.0-2.20180605git4a062cf.el8;x86_64;ubi-8-baseos-rpms
Installing: libfdisk;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Updating: libmount;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Updating: libsmartcols;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Installing: libsemanage;2.9-9.el8_6;x86_64;ubi-8-baseos-rpms
Installing: shadow-utils;2:4.6-17.el8;x86_64;ubi-8-baseos-rpms
Installing: libutempter;1.1.6-14.el8;x86_64;ubi-8-baseos-rpms
Installing: libedit;3.1-23.20170329cvs.el8;x86_64;ubi-8-baseos-rpms
Installing: gzip;1.9-13.el8_5;x86_64;ubi-8-baseos-rpms
Installing: cracklib;2.9.6-15.el8;x86_64;ubi-8-baseos-rpms
Installing: cracklib-dicts;2.9.6-15.el8;x86_64;ubi-8-baseos-rpms
Installing: libpwquality;1.4.4-6.el8;x86_64;ubi-8-baseos-rpms
Installing: pam;1.3.1-25.el8;x86_64;ubi-8-baseos-rpms
Installing: util-linux;2.32.1-42.el8_8;x86_64;ubi-8-baseos-rpms
Installing: openssh;8.0p1-19.el8_8;x86_64;ubi-8-baseos-rpms
Installing: openssh-clients;8.0p1-19.el8_8;x86_64;ubi-8-baseos-rpms
Installing: sshpass;1.09-4.el8;x86_64;ubi-8-appstream-rpms
Cleanup: libmount;2.32.1-39.el8_7;x86_64;installed
Cleanup: libblkid;2.32.1-39.el8_7;x86_64;installed
Cleanup: libuuid;2.32.1-39.el8_7;x86_64;installed
Cleanup: libsmartcols;2.32.1-39.el8_7;x86_64;installed
Complete.

(microdnf:1): librhsm-WARNING **: 13:31:59.096: Found 0 entitlement certificates

(microdnf:1): librhsm-WARNING **: 13:31:59.097: Found 0 entitlement certificates
Complete.
--> 8762968f8edc
[2/2] STEP 9/9: ENTRYPOINT ["entrypoint.sh"]
[2/2] COMMIT
--> d5fa9de87518
d5fa9de875186ea5dbbc3ecbfe19a8fdd5ba6c98e12ff76d4a5173f0237459cf
```

**Comment by adrianriobo** [comment]
Closed in favor of https://github.com/crc-org/crc/pull/3861/commits/18bb72868cc22e648ea1d51b2e94b22a353f5a70

**Pull request closed without merging**
