### PR TITLE
fix e2e result junit format

### PR DESCRIPTION
**Pull request by lilyLuLiu**
**Fixes:** Issue #4373

### CODE REVIEW

**Comment by cfergeau** [comment]
Can you provide more details about what's going wrong? It looks like we are getting malformed XML and are fixing it with sed? Is there a way to fix the input data so that it's well forme xml?

**Comment by adrianriobo** [comment]
Yeah not sure about this exact case, but what I can tell is that junit does not have a unified accepted xml schema it has several versions and depending on the tool it uses one or another, so may this is the reasoning for this, but if we do it here (customize it) we need to know which schema we will comply with.

**Comment by albfan** [comment]
What I detect reviewing the attach xml files is some tags are writed with `&#lt;` and `&#gt;`

I have to do similar replacements than Lu to have a readable text:

- `&#lt;`: <
- `&#gt;`: >
- `&#xA;`: \r

checking https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/

**Comment by albfan** [comment]
We have this info from reportportal maintainers: https://github.com/reportportal/reportportal/issues/1038

I just import one example with failures:

https://reportportal-openshiftlocal.apps.ocp-c1.prod.psi.redhat.com/ui/#openshift-local/launches/-2/1381/54689/54690/log?logParams=filter.gte.level%3DTRACE%26page.page%3D1

and basically `failure` tag ignores the `message` attribute and only adds as stacktrace what is inside `failure` tag

We only have the message attribute with the message from test. So a cleaner solution would be to transform xml to set the `message` value into `failure` content value

filter.xsl
```
<xsl:stylesheet version="1.0" 
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:strip-space elements="*"/>

<!-- identity transform -->
<xsl:template match="@*|node()">
    <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
</xsl:template>

<xsl:template match="failure">
    <xsl:copy>
        <xsl:value-of select="@message"/>
    </xsl:copy>
</xsl:template>

</xsl:stylesheet>
```

test.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="crc" tests="39" skipped="0" failures="2" errors="0" time="3272.246116512">
  <testsuite name="4 Openshift stories" tests="4" skipped="0" failures="0" errors="0" time="865.370507627">
    <testcase name="Overall cluster health" status="passed" time="681.654099201"></testcase>
    <testcase name="Mirror image to OpenShift image registry" status="passed" time="15.564511093"></testcase>
    <testcase name="Pull image locally, push to registry, deploy" status="passed" time="21.096793075"></testcase>
    <testcase name="Install new operator" status="passed" time="147.052302434"></testcase>
  </testsuite>
  <testsuite name="Basic test" tests="4" skipped="0" failures="1" errors="0" time="898.635556387">
    <testcase name="CRC version" status="failed" time="0.048058594">
      <failure message="Step stdout should contain correct version: output did not match. Expected: &#39;2.41.0+b0e3fb&#39;, Actual: &#39;CRC version: 24.10.01+b0e3fb&#xA;OpenShift version: 4.16.7&#xA;MicroShift version: 4.16.7&#39;"></failure>
    </testcase>
    <testcase name="CRC help" status="passed" time="0.032533415"></testcase>
    <testcase name="CRC status" status="passed" time="0.030564059"></testcase>
    <testcase name="CRC start usecase" status="passed" time="898.521600977"></testcase>
  </testsuite>
</testsuites>
```

```
xsltproc filter.xsl test.xml
```

result is:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="crc" tests="39" skipped="0" failures="2" errors="0" time="3272.246116512">
  <testsuite name="4 Openshift stories" tests="4" skipped="0" failures="0" errors="0" time="865.370507627">
    <testcase name="Overall cluster health" status="passed" time="681.654099201"/>
    <testcase name="Mirror image to OpenShift image registry" status="passed" time="15.564511093"/>
    <testcase name="Pull image locally, push to registry, deploy" status="passed" time="21.096793075"/>
    <testcase name="Install new operator" status="passed" time="147.052302434"/>
  </testsuite>
  <testsuite name="Basic test" tests="4" skipped="0" failures="1" errors="0" time="898.635556387">
    <testcase name="CRC version" status="failed" time="0.048058594">
      <failure>Step stdout should contain correct version: output did not match. Expected: '2.41.0+b0e3fb', Actual: 'CRC version: 24.10.01+b0e3fb
OpenShift version: 4.16.7
MicroShift version: 4.16.7'</failure>
    </testcase>
    <testcase name="CRC help" status="passed" time="0.032533415"/>
    <testcase name="CRC status" status="passed" time="0.030564059"/>
    <testcase name="CRC start usecase" status="passed" time="898.521600977"/>
  </testsuite>
</testsuites>
```

**Pull request closed without merging**
